### ISSUE TITLE
[BUG] No documentation for setup.py

### ISSUE THREAD

**Issue by danishjamal104** [code-gambit/VT-lambdas#15]
**Describe the bug**
No documentation regarding how to use setup.py.

Area Where Bug Occurred
- [ ] Lambda <@<mention name of lambda here if selected>>
- [ ] DynamodDb
- [x] Documentation

**Additional context**
There must exist documentation on how to use the `setup.py` script to build and create new lambdas.

**Before submitting an issue check the below**
- [x] I have synced all my node versions as mentioned in the project"
- [x] I am using the same version of npm as is the project

**Comment by danishjamal104** [comment]
can I work on this?? @ayush0x00 and @lakshya-20 ??

**Comment by ayush0x00** [comment]
I have modified the setup.py file to ask for a directory name before setting up the lambda. Have a look on that before documenting.

**Comment by danishjamal104** [comment]
> I have modified the setup.py file to ask for a directory name before setting up the lambda. Have a look on that before documenting.



does that input have any significance, while building??

**Comment by ayush0x00** [comment]
Nopes. Although I did use chdir command. You can have a look from line 111 to 122

**Comment by danishjamal104** [comment]
@ayush0x00 can we store all lambdas in a single folder without having a nested structure??

**Comment by danishjamal104** [comment]
Also @lakshya-20 and @ayush0x00 , please suggest where should I keep the file??
Should I create a separate md or update the readme itself.

**Comment by ayush0x00** [comment]
Keep updating in readme
