### ISSUE TITLE
[BUG] No check on lambda while building the lambdas using setup.py

### ISSUE THREAD

**Issue by danishjamal104** [code-gambit/VT-lambdas#16]
**Describe the bug**
While building the lambda there is no check on the directory if its lambda or not for example currently the folder `user_access_patterns` is not a lambda but after running the build command it will treat that directory as a lambda hence the lambda check on the directory is missing in `build` function refer to line 63 of `setup.py`.

Area Where Bug Occurred
- [ ] Lambda <@<mention name of lambda here if selected>>
- [ ] DynamodDb
- [X] setup.py 

**How to reproduce the error/bug**
1. Create a non-lambda directory inside lambda folder `lambda/new_not_lambda_dir`
2. Execute the build command `python setup.py -b .`

**Screenshot**<br>
<img width="922" alt="Screenshot 2021-04-08 at 6 31 12 PM" src="https://user-images.githubusercontent.com/31315800/114031050-9a883200-9898-11eb-8211-bec6f4c2f152.png">

**Before submitting an issue check the below**
- [x] I have synced all my node versions as mentioned in the project"
- [x] I am using the same version of npm as is the project

**Comment by danishjamal104** [comment]
I would like to work on this. @lakshya-20 , @ayush0x00 please assign it to me.

**Comment by ayush0x00** [comment]
Done.
