### ISSUE TITLE
Lambda for file_access_patterns

### ISSUE THREAD

**Issue by ayush0x00** [code-gambit/VT-lambdas#20]
**Describe the purpose**
The lambda uploadFile and deleteFile will be used to upload a new file by user and delete an existing file.

**Possible Implementation**
Simple implementation based on async calls and dynamodb queries.

**Comment by ayush0x00** [comment]
@danishjamal104 @lakshya-20 Please assign me this

**Comment by danishjamal104** [comment]
> @danishjamal104 @lakshya-20 Please assign me this

go ahead

**Comment by lakshya-20** [comment]
@ayush0x00 I think I have done the required changes please have a look [https://github.com/code-gambit/VT-lambdas/pull/33](https://github.com/code-gambit/VT-lambdas/pull/33)

**Comment by danishjamal104** [comment]
Below 4 file related lambdas are already implemented:
1. lambda_for_fileDelete : deleting files
2. lambda_for_fileDetails : accessing file details
3. lambda_for_fileList : fetch list of files(supports time series query)
4. lambda_for_fileUpload : uploading file details

Do we have any more use cases related to files? If no then we should close this.

**Comment by lakshya-20** [comment]
Currently `lambda_for_fileList` does not support time-series query. We can close this issue and can open another one particular for this.

**Comment by danishjamal104** [comment]
sure
