### ISSUE TITLE
[BUG] Apply changes according to the latest database modelling

### ISSUE THREAD

**Issue by lakshya-20** [code-gambit/VT-lambdas#32]
**Describe the bug**
- Modify `CreateTable.js` script as per the latest database modelling.
- Update `model.md` as per the new table design.
- Check/Update query operations according to the latest schema for all lambdas.

Area Where Bug Occurred
- [X] Lambda 
- [X] DynamodDb

**Before submitting an issue check the below**
- [X] I have synced all my node versions as mentioned in the project"
- [X] I am using the same version of npm as is the project

**Comment by lakshya-20** [comment]
@ayush0x00 can I work on this?

**Comment by danishjamal104** [comment]
> @ayush0x00 can I work on this?

go ahead
