### ISSUE TITLE
[BUG] Update timestamp generator

### ISSUE THREAD

**Issue by lakshya-20** [code-gambit/VT-lambdas#37]
**Describe the bug**
The timestamp should be generated such that it is in `YYYY-MM-DD-HH-mm-ss` format if there is any single digit in the timestamp append a `0` before it. Like if the original timestamp is like `2021-4-21-2-50-8`  it should be converted to `2021-4-21-02-50-08`.

Area Where Bug Occurred
- [X] Lambda <@lambda_for_fileUpload>
- [ ] DynamodDb

**How to reproduce the error/bug**
Use `date-and -time` library refer [https://www.npmjs.com/package/date-and-time](https://www.npmjs.com/package/date-and-time)

**Additional context**
Storing timestamp according to the proposed way can help in getting the files sorted on the basis of timestamp.

**Before submitting an issue check the below**
- [X] I have synced all my node versions as mentioned in the project"
- [X] I am using the same version of npm as is the project

**Comment by ayush0x00** [comment]
Is this issue resolved? @lakshya-20

**Comment by lakshya-20** [comment]
Yes
