### ISSUE TITLE
rename exports module for each lambda to handler

### ISSUE THREAD

**Issue by ayush0x00** [code-gambit/VT-lambdas#47]
**Describe the bug**
The export modules have different names for different lambda. This may cause plenty of manual work while calling lambda. So its good idea to rename every exports to default name handler

**Before submitting an issue check the below**
- [x] I have synced all my node versions as mentioned in the project"
- [x] I am using the same version of npm as is the project

**Comment by danishjamal104** [comment]
I think this issue is already resolved. @lakshya-20 and @ayush0x00 ?

**Comment by danishjamal104** [comment]
Should we close this?

**Comment by lakshya-20** [comment]
Yes, we are good to go, no need for this issue anymore.
