### ISSUE TITLE
[BUG] response update for GET endpoint /user/{userId}/file

### ISSUE THREAD

**Issue by danishjamal104** [code-gambit/VT-lambdas#57]
**Describe the bug**
Currently the GET endpoint `/user/{userId}/file` returns the below response 
```json
{
    "statusCode":200,
    "body":{
        "items":[
            {
                "LS1_SK":"string",
                "size":0,
                "f_type":"string",
                "hash":"string",
                "SK":"FILE#2021-05-07-19-34-10",
                "PK":"USER#ce62edbe-5fa9-4d3d-9f36-ed04bb819f01"
            }
        ]
    }
}
```
since the body has a single child, hence no need to add `items` that as a key simply make the body as the list of items.

Area Where Bug Occurred
- [x] Lambda <@lambda_for_fileList>
- [ ] DynamodDb

**Additional context**
Example response
```json
{
    "statusCode":200,
    "body":[
        {
            "LS1_SK":"string",
            "size":0,
            "f_type":"string",
            "hash":"string",
            "SK":"FILE#2021-05-07-19-34-10",
            "PK":"USER#ce62edbe-5fa9-4d3d-9f36-ed04bb819f01"
        }
    ]
}
```

**Before submitting an issue check the below**
- [x] I have synced all my node versions as mentioned in the project"
- [x] I am using the same version of npm as is the project

**Comment by lakshya-20** [comment]
We are returning `lastEvaluatedKey` also so we need to have file data under `body.items` and `lastEvaluatedKey` under `body.LastEvaluatedKey`.

**Comment by danishjamal104** [comment]
I am closing this the, we already had a discussion.
