### ISSUE TITLE
[BUG] Minor change in fileList lambda

### ISSUE THREAD

**Issue by lakshya-20** [code-gambit/VT-lambdas#59]
**Describe the bug**
Modify `lambda_for_fileList` to access `LastEvaluatedKey` through query parameter instead of request body.

Area Where Bug Occurred
- [X] Lambda <@lambda_for_fileList>

**How to reproduce the error/bug**
```sh 
const lastEvaluatedKey = base64ToJson(event.query.LastEvaluatedKey);
```

**Additional context**
Get request cannot have a request body.

**Before submitting an issue check the below**
- [X] I have synced all my node versions as mentioned in the project"
- [X] I am using the same version of npm as is the project

**Comment by ayush0x00** [comment]
If you are working on this issue, please modify the urlList lambda. It has similar bug.
