### ISSUE TITLE
[BUG] auto generate url when file is uploaded

### ISSUE THREAD

**Issue by danishjamal104** [code-gambit/VT-lambdas#65]
**Describe the bug**
As the main motive of this application is an easy and fast way of sharing files. The current implementation allows users to upload files and then separately generate URLs, instead what should be done is their must one URL which is the default one and it is autogenerated whenever the file is uploaded, it will be a public URL and be included in the files model itself. In this way, every time a user uploads a file he/she gets the default URL making the user experience better.

**Before submitting an issue check the below**
- [x] I have synced all my node versions as mentioned in the project"
- [x] I am using the same version of npm as is the project

**Comment by danishjamal104** [comment]
what are your suggestions @lakshya-20 and @ayush0x00 ?

**Comment by lakshya-20** [comment]
Looks good.
What's is the meaning of file model?

**Comment by danishjamal104** [comment]
> Looks good.
> What's is the meaning of file model?

as discuss, file schema

**Comment by danishjamal104** [comment]
what is progress @lakshya-20 ??

**Comment by danishjamal104** [comment]
I am working on this issue. @ayush0x00
